fun main() {
    var t0 = System.currentTimeMillis()

    fun d(s: String) {
        println("\nDay $s\n========\n")
        t0 = System.currentTimeMillis()
    }
    fun e() {
        val d = System.currentTimeMillis() - t0
        println("\ntime: ${d}ms\n")
    }

    d("01.a"); day01.a.main(); e()
    d("01.b"); day01.b.main(); e()
    d("02.a"); day02.a.main(); e()
    d("02.b"); day02.b.main(); e()
    d("03.a"); day03.a.main(); e()
    d("03.b"); day03.b.main(); e()
    d("04.a"); day04.a.main(); e()
    d("04.b"); day04.b.main(); e()
    d("05.a"); day05.a.main(); e()
    d("05.b"); day05.b.main(); e()
    d("06.a"); day06.a.main(); e()
    d("06.b"); day06.b.main(); e()
    d("07.a"); day07.a.main(); e()
    d("07.b"); day07.b.main(); e()
    d("08.a"); day08.a.main(); e()
    d("08.b"); day08.b.main(); e()
    d("09.a"); day09.a.main(); e()
    d("09.b"); day09.b.main(); e()
    d("10.a"); day10.a.main(); e()
    d("10.b"); day10.b.main(); e()
    d("11.a"); day11.a.main(); e()
    d("11.b"); day11.b.main(); e()
    d("12.a"); day12.a.main(); e()
    d("12.b"); day12.b.main(); e()
    d("13.a"); day13.a.main(); e()
    d("13.b"); day13.b.main(); e()
    d("14.a"); day14.a.main(); e()
    d("14.b"); day14.b.main(); e()
    d("15.a"); day15.a.main(); e()
    d("15.b"); day15.b.main(); e()
    d("16.a"); day16.a.main(); e()
    d("16.b"); day16.b.main(); e()
    d("17.a"); day17.a.main(); e()
    d("17.b"); day17.b.main(); e()
    d("18.a"); day18.a.main(); e()
    d("18.b"); day18.b.main(); e()
    d("19.a"); day19.a.main(); e()
    d("19.b"); day19.b.main(); e()
//    d("20.a"); day20.a.main(); e()
//    d("20.b"); day20.b.main(); e()
//    d("21.a"); day21.a.main(); e()
//    d("21.b"); day21.b.main(); e()
//    d("22.a"); day22.a.main(); e()
//    d("22.b"); day22.b.main(); e()
//    d("23.a"); day23.a.main(); e()
//    d("23.b"); day23.b.main(); e()
//    d("24.a"); day24.a.main(); e()
//    d("24.b"); day24.b.main(); e()
//    d("25.a"); day25.a.main(); e()
//    d("25.b"); day25.b.main(); e()


}